services:
  postgres:
    image: pgvector/pgvector:0.6.2-pg15
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c max_connections=100
               -c shared_buffers=512MB
               -c effective_cache_size=1536MB
               -c maintenance_work_mem=128MB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=-1
               -c default_statistics_target=100
               -c huge_pages=off
               -c effective_io_concurrency=200
               -c work_mem=512MB
               -c min_wal_size=1GB
               -c max_wal_size=4GB
               -c checkpoint_timeout=2min
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  
  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
